### ISSUE TITLE
Jumping to a non existent marker will halt specbas

### ISSUE THREAD

**Issue by ASH-II** [ZXDunny/SpecBAS#11]
In the menu bar you cant jump to a non existent marker but the shortcut keys will try to.
this will crash specbas from the Direct command window.
I.E. a new specbas , direct command , press Ctrl+F1....hang

**Comment by ZXDunny** [comment]
Thanks. Should be fixed now.

**Comment by ASH-II** [comment]
YEP. that works now :)
