### ISSUE TITLE
CENTRE+INVERSE chops off chrs

### ISSUE THREAD

**Issue by ASH-II** [ZXDunny/SpecBAS#12]
10 PRINT CENTRE 10;"HELLO WORLD"
20 PRINT CENTRE 12;INVERSE 1;"HELLO WORLD"

spot the fault :)

**Comment by ZXDunny** [comment]
Thanks, fixed. All 1/0 PRINT items (such as BOLD, ITALIC, INVERSE, OVER etc) were storing the wrong number of characters (should be four, were storing only one). This caused the PRINT handler to skip the next couple of characters.

Please test and close if it's fixed.

**Comment by ASH-II** [comment]
Fixed 👍
