### ISSUE TITLE
parts of editor not locked

### ISSUE THREAD

**Issue by ASH-II** [ZXDunny/SpecBAS#13]
If you create a new font and select it parts of the editor are affected by it.
the menu bar
the char coords...

FONT NEW a,8,8,FONT_MONO
FONT a
will blank out parts of the editor.
obviously FONT 1 will restore it.

**Comment by ZXDunny** [comment]
Editor-created controls were using the wrong font (the currently selected user font) instead of the default system font. This is now fixed.

**Comment by ASH-II** [comment]
yeah. fixed... :-)
