### ISSUE TITLE
SpecBAS crashed and now won't restart

### ISSUE THREAD

**Issue by simonsnake** [ZXDunny/SpecBAS#19]
SpecBAS crashed while I was editing a program. I closed the window. When I reopened SpecBAS I just get the blank grey screen and while the mouse cursor moves around, that's all I get.

I tried the non-64 bit executable, then I downloaded your december 2019 version and they all now just open a blank grey window but with nothing happening.

It's a shame as I was trying some code to help me find sudoku candidates and now I'm stuck.

It's as if there's something wrong with the 'saved state' that occurs between closing and reopening where it now can't restore the previous session.

Run CreateData.bas first which will set up 9 arrays of data, and then try the second program. I was just about to edit the code between lines 240 to 320 as I've not got it incrementing the elements of the z() array correctly based on the values stored in the other 9 loaded arrays when the crash happened.

[Sudoku Combinations.zip](https://github.com/ZXDunny/SpecBAS/files/5191225/Sudoku.Combinations.zip)

**Comment by ZXDunny** [comment]
Sorry to hear that. Here's what I need you to do:

1. Head to c:\users\<username>\specbas\s (where your logged in windows username replaces <username>) and send me the file "autosave" - it's text, you can attach it by email to paul.dunn@gmail.com - if there are other files in there then feel free to send those too, but they shouldn't really matter.

2. Delete the file(s) - the SpecBAS should start just fine.

**Comment by ZXDunny** [comment]
Should be fixed now.
