### ISSUE TITLE
POKE USR issue? 

### ISSUE THREAD

**Issue by shenshendrax** [ZXDunny/SpecBAS#20]
I noticed that SpecBAS doesnt accept this line while entering as valid and puts a red spot next to it. 

`POKE USR "k"+t,n `

works in BASin.

**Comment by ZXDunny** [comment]
SpecBAS isn't a Spectrum emulator, and BASin is. 

Sinclair BASIC's UDGs are 8 bytes each, SpecBAS's are 64 bytes for the default font. You can load up the "demos:graphics/sprites" demo to see an example of making UDGs in SpecBAS.

USR doesn't exist in SpecBAS as you can't call machine code routines (they wouldn't work as there's no z80) and POKE only works on memory banks and has the syntax POKE BankID, Address, Value.
