### ISSUE TITLE
Missing SpecBAS_x64.exe

### ISSUE THREAD

**Issue by sammymitchell** [ZXDunny/SpecBAS#22]
The installation instructions note:
"and copy the following files in there: SpecBAS.exe SpecBAS_x64.exe Bass.dll Bass64.dll What's New.txt"

But SpecBAS_x64.exe is missing. SpecBAS_32.exe is there, however.

**Comment by ZXDunny** [comment]
SpecBAS.exe is the 64 bit build, and SpecBAS_32.exe is the 32bit. I'll amend the document.
