### ISSUE TITLE
screen grab?

### ISSUE THREAD

**Issue by ASH-II** [ZXDunny/SpecBAS#3]
Hi Paul
Is SCREEN GRAB working correctly?

10 PRINT AT 0,0;"A"
20 SCREEN GRAB a$,0,0,8,8
30 WINDOW PUT a$,0,0,0 SCALE 4

gives a black square at the scale asked instead of a larger "A"

**Comment by ZXDunny** [comment]
SCREEN GRAB has been deprecated, as it is no longer possible to do.

It basically grabs the screen - including all windows and sprites. This means that it would need more than 256 colours - each window can have its own palette. 

Use WINDOW GRAB var$,id,x,y,w,h [,t] instead. Sprites will not be included though, and won't grab overlapping windows.

**Comment by ASH-II** [comment]
Ahh right , I can work around that...
