### ISSUE TITLE
Startup_Sequence

### ISSUE THREAD

**Issue by ASH-II** [ZXDunny/SpecBAS#4]
Hi Paul
If you start specbas with a clean install,
It doesn't create a Startup_sequence in the "s" folder. and I can't find the sysfiles.zip
EDIT: found it in my backup folder :)

the blurb on the code page explains how to change your font size in line 60 of the startup_sequence but I'm not getting that file in the "s" folder ?

**Comment by ZXDunny** [comment]
sysfiles.zip will be added in the next release - thanks :)

**Comment by ASH-II** [comment]
I can't get the text bigger in my startup
I have tried to use this...

ZXASCII
AUTO -1
PROG startup-sequence
10 REM Startup option commands can be set here
20 screen window 1024,768
30 option intscaling,1
50 rem WINDOW size 0,640,480
60 option edfontscalex,4
70 option edfontscaley,4

but the text stays the same.

**Comment by ZXDunny** [comment]
put the options in quotes.

OPTION "intscaling",1
OPTION "edfontscalex",4

etc, etc
