### ISSUE TITLE
loading sprites

### ISSUE THREAD

**Issue by ASH-II** [ZXDunny/SpecBAS#6]
Hi Paul
I have created a sprite and when I try and load it back into Specbas after saving it as a bank it crashes specbas.

the file is attached (in a zip) and the line of code I am using is
10 LOAD "laser" BANK NEW laser

[laser.zip](https://github.com/ZXDunny/SpecBAS/files/4092766/laser.zip)

**Comment by ZXDunny** [comment]
The good news is that there's nothing wrong with the sprite. The bad news is that for some reason if I debug my way through the loading routine, everything is fine. If I run it without debugging, it crashes. 

Watch this space.

**Comment by ZXDunny** [comment]
This should now be fixed. It was a case of copying from one buffer to another but using the wrong size - about 14 bytes too much for the source buffer which led to weirdness (as you'd expect).

If it's fixed, then we can close this one.

**Comment by ASH-II** [comment]
yep thats working now thanks Paul
