### ISSUE TITLE
sprites still iffy :) and small screen's muck up the editor

### ISSUE THREAD

**Issue by ASH-II** [ZXDunny/SpecBAS#7]
![small window](https://user-images.githubusercontent.com/58967719/75627763-0d6da680-5bcb-11ea-9923-d47802d25e30.jpg)
Hi paul
trying your latest build and if I make the screen small (500,750) and the editor menu goes off the screen if I select the right most menu it messes up...you can't scroll the variable window and the menu's don't auto hide, see pic

and when I made a new sprite after your fix it failed to load again.

file attached

[laser2.zip](https://github.com/ZXDunny/SpecBAS/files/4271916/laser2.zip)

**Comment by ZXDunny** [comment]
Thanks, I'll get on it.

**Comment by ZXDunny** [comment]
What happens when you load it? When I use LOAD "laser2" BANK then I get a new sprite using the laser in greeen. 

There is a problem where using say, LOAD "laser2" BANK 18 will pop it in bank 7, and then for some reason it gets converted to a window.

**Comment by ASH-II** [comment]
Yeah just had a check and it was bad , bad programming by me.
I not telling you how bad as you will not believe me....working now 😊

Ste.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ZXDunny** [comment]
You're still gonna have to let me know what you did and why it failed - at least so I can make sure there's no bug in there :)

And any suggestions as to how syntax could be changed would be useful too.

**Comment by ASH-II** [comment]
If you must know I was loading in a wrong file....and only realised when you mentioned the file name and it didn't match mine....(facepalm)

**Comment by ZXDunny** [comment]
Ok, the weird "sprite turns into a window bank" bug is now fixed, but the "menu in way too small a window" issue is still out there. I'll see what I can do about that.

**Comment by ASH-II** [comment]
I think I might of found my problem....
this program shows it better.

10 CLEAR: LET a=1:print scale 2,2; at 25,8;"          PRESS="   
20 GO SUB @space
30 LOAD "jetpac/ly" BANK 6
40 GO SUB @space
50 SPRITE MOVE 6 TO 0,0
60 GO SUB @space
70 LOAD "jetpac/lg" BANK 7
80 GO SUB @space
90 SPRITE MOVE 7 TO 0,16
100 GO SUB @space
110 LOAD "jetpac/lb" BANK 8
120 GO SUB @space
130 SPRITE MOVE 8 TO 0,32
140 GO SUB @space
150 STOP
160 LABEL @space
170 IF a=0 AND INKEY$="b" THEN LET a=1: RETURN 
180 IF a=1 THEN IF INKEY$="a" THEN LET a=0: RETURN 
190 PRINT AT 50,50;SCALE 4,4;PAPER RND*256;CHR$(CODE "b"-a)
200 GO TO 170

The above program loads in three different sprints and moves them so they are not on top off each other but when the second sprite is loaded in, the first sprite stops showing or animating and when the third sprite loads in the second sprite stops showing or animating and I don't know why,
press "a" and "b" to step through the program.
[Jetpac.zip](https://github.com/ZXDunny/SpecBAS/files/4332876/Jetpac.zip)

**Comment by ZXDunny** [comment]
Ok, that was a tough one but a one-line fix after all - when loading a sprite, make sure its ID byte is filled correctly so the system can make use of it.

New binary has been pushed to the front page.

**Comment by ASH-II** [comment]
Yeah I'm not going simple , Thanks Paul
when I loaded "Laser2" it worked because I was loading one sprite but in my program it's called lb and ly and lg but I thought I was loading something different than Laser2

All Good :)
