### ISSUE TITLE
your debug labels keep adding to the next line

### ISSUE THREAD

**Issue by ASH-II** [ZXDunny/SpecBAS#8]
I think this photo tells it all
![labels](https://user-images.githubusercontent.com/58967719/77224153-a8b6c380-6b5a-11ea-8eae-6706c5ba5d9c.jpg)

also just the first one will link to a label because the others have wrong names and cause an access violation if double clicked :)
![label2](https://user-images.githubusercontent.com/58967719/77224232-76f22c80-6b5b-11ea-99f3-a90f7dc4c273.jpg)

**Comment by ZXDunny** [comment]
Fixed, many thanks. Please test and close if all is Ok.

**Comment by ASH-II** [comment]
Fixed :)
