### ISSUE TITLE
This hangs specbas and my display settings

### ISSUE THREAD

**Issue by ASH-II** [ZXDunny/SpecBAS#9]
20 SCREEN FULL 1024,768 SCALE 4,4

not quite sure how this works but if I run this and move my mouse it shows fullscreen coloured blocks and hangs, have to (Windows/D) and then close specbas, and then change my display back.

I have created a window (255,191) and want to stretch it to 1024,768 and the specos doesn't have the newer commands.

**Comment by ZXDunny** [comment]
That's because you're trying to open a 4x4 window. Try instead:

20 SCREEN FULL 1024,768 SCALE 256,192

**Comment by ASH-II** [comment]
:)
